### ISSUE TITLE
Disable saving of TTYREC files

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/dgamelaunch#4]
They are useless if you cannot replay them.

Or are they needed for watch current games option?

**Comment by TommiGustafsson-HMP** [comment]
This probably is not needed if we enlarge Amazon AWS instance HDD space.

**Comment by janne-hmp** [comment]
Deferred.

**Comment by TommiGustafsson-HMP** [comment]
Amazon AWS instances have now 25 GB disk space.
