### ISSUE TITLE
Two commands to set options to defaults: Curses Interface and Normal TTY 

### ISSUE THREAD

**Issue by TommiGustafsson-HMP** [hyvanmielenpelit/dgamelaunch#6]
d) Set options to normal TTY defaults
u) Set options to Curses interface defaults

First one copies the normal defaults file and overwrites your current options. There is a command prompt, "Do you want to set your options to normal TTY defaults? (y/N)"

The second one copies the Curses interface defaults file and overwrites your current options. There is a command prompt, "Do you want to set your options to Curses interface defaults? (y/N)" After answering yes, it also tells that "Please set your SSH client remote character set to CP437 and set your terminal size to 120x34."

I think we do not need defaults for TTY IBMgraphics #3 . It is easy enough to set manually.

**Comment by janne-hmp** [comment]
Looks like this is now ok.
